# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/paulo101977/project/sdlarchrl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/paulo101977/project/sdlarchrl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paulo101977/project/sdlarchrl/CMakeFiles /home/paulo101977/project/sdlarchrl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paulo101977/project/sdlarchrl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named pcsx2_headless

# Build rule for target.
pcsx2_headless: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pcsx2_headless
.PHONY : pcsx2_headless

# fast build rule for target.
pcsx2_headless/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcsx2_headless.dir/build.make CMakeFiles/pcsx2_headless.dir/build
.PHONY : pcsx2_headless/fast

#=============================================================================
# Target rules for targets named _retro

# Build rule for target.
_retro: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _retro
.PHONY : _retro

# fast build rule for target.
_retro/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_retro.dir/build.make CMakeFiles/_retro.dir/build
.PHONY : _retro/fast

glad.o: glad.c.o
.PHONY : glad.o

# target to build an object file
glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_retro.dir/build.make CMakeFiles/_retro.dir/glad.c.o
.PHONY : glad.c.o

glad.i: glad.c.i
.PHONY : glad.i

# target to preprocess a source file
glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_retro.dir/build.make CMakeFiles/_retro.dir/glad.c.i
.PHONY : glad.c.i

glad.s: glad.c.s
.PHONY : glad.s

# target to generate assembly for a file
glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_retro.dir/build.make CMakeFiles/_retro.dir/glad.c.s
.PHONY : glad.c.s

sdlarch.o: sdlarch.cpp.o
.PHONY : sdlarch.o

# target to build an object file
sdlarch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcsx2_headless.dir/build.make CMakeFiles/pcsx2_headless.dir/sdlarch.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_retro.dir/build.make CMakeFiles/_retro.dir/sdlarch.cpp.o
.PHONY : sdlarch.cpp.o

sdlarch.i: sdlarch.cpp.i
.PHONY : sdlarch.i

# target to preprocess a source file
sdlarch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcsx2_headless.dir/build.make CMakeFiles/pcsx2_headless.dir/sdlarch.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_retro.dir/build.make CMakeFiles/_retro.dir/sdlarch.cpp.i
.PHONY : sdlarch.cpp.i

sdlarch.s: sdlarch.cpp.s
.PHONY : sdlarch.s

# target to generate assembly for a file
sdlarch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcsx2_headless.dir/build.make CMakeFiles/pcsx2_headless.dir/sdlarch.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_retro.dir/build.make CMakeFiles/_retro.dir/sdlarch.cpp.s
.PHONY : sdlarch.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... _retro"
	@echo "... glad"
	@echo "... pcsx2_headless"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... sdlarch.o"
	@echo "... sdlarch.i"
	@echo "... sdlarch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

